### ISSUE TITLE
Theme background images break styling

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-visua11y#38]
Theme background images should be in their own element rather. This is to prevent filters from bleeding into their descendants.

**Comment by oliverfoster** [comment]
Make compatible with latest boxMenu and vanilla.

**Comment by joe-replin** [comment]
I also have run into an issue in relation to #33 & this issue. When toggling a media component full screen while media was in its pre-played (poster image) state, the full screen poster image and video would stretch a to the height of the page. 

I'm filing my issue here because it is related and I wanted to raise awareness. I'm hoping this fix will correct that as well. Here's what I was working with:

- FW v5.19.6
- Media v5.4.1
- Visua11y v1.1.1

My temporary fix was to make '.page' the targeted parent instead of <html> within lines 10 & 30 of modifiers.less.

**Comment by swashbuck** [comment]
@joe-replin Is your comment still relevant? If so, maybe that could be a new issue and we can close this one?

**Comment by joe-replin** [comment]
Yup. Go ahead and close this one. My issue from last year seems to be corrected now.
